### ISSUE TITLE
sort_keys arg

### ISSUE THREAD

**Issue by dckc** [madzak/python-json-logger#44]
A `sort_keys` would be nice.

I know I can implement it myself with a few lines of code, but that doesn't work from a logging config file.

**Comment by tuukkamustonen** [comment]
Wouldn't you need `OrderedDict` (or py 3.6 with ordered dicts as *implementation detail*) for that?

**Comment by tuukkamustonen** [comment]
Ahem, ignore my stupid question. `json.dumps(..., sort_keys=...)` does the magic directly on string output so yeah, need nothing special and would be cool.

**Comment by offero** [comment]
Yes, use sort_keys. Making a new OrderedDict for each log output would be a large overhead.

**Comment by dckc** [comment]
I don't understand. How do you recommend I use sort_keys from a logging config file? I don't see any way to do that.

**Comment by dclar43** [comment]
I'd like this feature as well and I'm kind of confused why this was closed.  
  
@tuukkamustonen said that `OrderedDict` wouldn't need to be used because passing `sort_keys=True` to `json.dumps` handles the sorting.   
  
Then @offero said   
  
> Yes, use sort_keys. Making a new OrderedDict for each log output would be a large overhead.  
  
and closed it. Which doesn't really make sense to me. Maybe I'm misunderstanding something.  
  
As far as I can tell the only way we can effectively call `json.dumps` with  `sort_keys=True` is to pass our own `json_serializer` to `JsonFormatter`.   
  
Some **brief** profiling:  
  
Test data is from a JSON file containing 8000 randomly generated entries(generated using https://www.json-generator.com) into a dict.  
  
I ran both `json.dumps(data)` and `json.dumps(data, sort_keys=True)` 100 times.  
  
The former spent a total time of 14,554ms in `iterencode` while the ladder spent 16,580ms in `iterencode`.  
  
So on average not sorting took 145.54ms and sorting took 165.8ms resulting in a 20.26ms difference between the two.  
  
These numbers are from Python 3.7 but Python 3.5 showed similar results.
