### ISSUE TITLE
missing timestamp? severity obeyed?

### ISSUE THREAD

**Issue by bitsofinfo** [madzak/python-json-logger#69]
Hi 
Just trying out this library, perhaps I'm missing something in the docs:

I don't see any timestamp or severity in the emitted log statement:

I just get `{"message": "hello"}`

```
import logging
import sys
from pythonjsonlogger import jsonlogger

logger = logging.getLogger()

logHandler = logging.StreamHandler(sys.stdout)
formatter = jsonlogger.JsonFormatter()
logHandler.setFormatter(formatter)
logger.addHandler(logHandler)
logger.setLevel("INFO")

logger.warn("hello")
```

Do i have to manually handle this standard stuff myself like your `CustomJsonFormatter` and if so, how do I get the record creating timestamp, vs creating my own which would have a delay?

**Comment by kini** [comment]
When you create `JsonFormatter`, pass in a format string in the % format, containing references to whatever fields you want the JSON formatter to produce. Recognized field names are [the same ones `logging` uses](https://docs.python.org/3/library/logging.html#logrecord-attributes). The fields you want for severity and timestamp would be `levelname` and `created` respectively, so create the `JsonFormatter` as follows:

```python
formatter = jsonlogger.JsonFormatter('%(message)s %(levelname)s %(created)f')
```

produces

```
{"message": "hello", "levelname": "WARNING", "created": 1551812659.682081}
```

(Actually the library just grabs anything wrapped in parentheses, so you could just as well use `'(levelname)(created)'` if you wanted.)

As a special case, the library is able to convert timestamps from their original, "floating point number of seconds since the Unix epoch" format into an ISO 8601 string. You can do this as follows:

```python
formatter = jsonlogger.JsonFormatter('%(message)s %(levelname)s', timestamp=True)
```

produces

```
{"message": "hello", "levelname": "WARNING", "timestamp": "2019-03-05T19:10:15.903588"}
```
